Repository DogCatWorldTeam/backend, pull requests merged in 2024-07, with the labels that each got.

#77 feat: 펫 장례식장 공공데이터 api
  build.gradle
  src/main/java/com/techeer/abandoneddog/funeral/controller/PetFuneralController.java
  src/main/java/com/techeer/abandoneddog/funeral/service/PetFuneralService.java
  src/main/resources/funeralData/PetFuneralData.xls
Labels: Feat

#74 feat: 회원가입 유효성 검사 추가
  src/main/java/com/techeer/abandoneddog/users/controller/UserController.java
Labels: Feat

#81 feat: Prometheus/grafana 구성
  build.gradle
  docker-compose.yml
  src/main/resources/application.yml
  src/main/resources/prometheus.yml
Labels: Feat

#80 fIx: 펫게시판 상세조회 petInfo 수정
  src/main/java/com/techeer/abandoneddog/pet_board/dto/PetBoardDetailResponseDto.java
Labels: Fix

#84 fix:상세조회 수정
  src/main/java/com/techeer/abandoneddog/animal/PetInfoDto/PetInfoResponseDto.java
  src/main/java/com/techeer/abandoneddog/pet_board/dto/PetBoardDetailResponseDto.java
  src/main/java/com/techeer/abandoneddog/pet_board/dto/PetBoardResponseDto.java
Labels: Fix

#88 fix: 펫 게시글 최신순 정렬
  src/main/java/com/techeer/abandoneddog/pet_board/controller/PetBoardController.java
Labels: Fix

#89 feat: S3 이미지 리사이징 db 저장
  docker-compose.yml
  src/main/java/com/techeer/abandoneddog/animal/entity/PetInfo.java
  src/main/java/com/techeer/abandoneddog/animal/repository/PetInfoRepository.java
  src/main/java/com/techeer/abandoneddog/global/config/CorsConfig.java
  src/main/java/com/techeer/abandoneddog/global/config/S3Config.java
  src/main/java/com/techeer/abandoneddog/image/dto/ImageResizingDto.java
  src/main/java/com/techeer/abandoneddog/image/entity/Image.java
  src/main/java/com/techeer/abandoneddog/image/repository/ImageRepository.java
  src/main/java/com/techeer/abandoneddog/pet_board/controller/PetBoardController.java
  src/main/java/com/techeer/abandoneddog/pet_board/service/PetBoardService.java
  src/main/java/com/techeer/abandoneddog/s3/S3Service.java
Labels: Feat

#91 [refactor] QueryDSL 북마크 조회 리펙토링
  build.gradle
  src/main/java/com/techeer/abandoneddog/bookmark/controller/BookmarkController.java
  src/main/java/com/techeer/abandoneddog/bookmark/repository/BookmarkCustomRepository.java
  src/main/java/com/techeer/abandoneddog/bookmark/repository/BookmarkCustomRepositoryImpl.java
  src/main/java/com/techeer/abandoneddog/bookmark/repository/BookmarkRepository.java
  src/main/java/com/techeer/abandoneddog/bookmark/service/BookmarkService.java
  src/main/java/com/techeer/abandoneddog/global/config/CorsConfig.java
Labels: Refactor
